archivo = open("C:\\Users\\B09S202est\\Documents\\Programacion2026\\prog-2610-unidad5-sebas441\\ejercicios\\log.txt", "a")
texto = input("Ingresa una frase: ")
edad = int(input("Ingresa tu edad: "))
estatura = float(input("Ingresa tu estatura: "))
archivo.write(texto)
# archivo.write(f"{edad}\n")
archivo.write(str(edad)+"\n")
archivo.write(str(estatura)+"\n")
archivo.close()